// <auto-generated />
namespace NUS.TheAmagingRace.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newName));
        
        string IMigrationMetadata.Id
        {
            get { return "201805021212355_newName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
